version: '3.8'

services:
  indexer:
    # Baut das Image basierend auf dem Dockerfile
    build: .
    # Lädt die Umgebungsvariablen aus der .env-Datei
    env_file:
      - .env
    # Mountet den lokalen Code in den Container
    volumes:
      - .:/app
    # Stellt sicher, dass der PYTHONPATH beim Start gesetzt wird,
    # um die im Dockerfile isolierten Abhängigkeiten zu finden.
    command: /bin/bash -c "PYTHONPATH=$$PYTHON_DEPENDENCIES_PATH python indexer.py"
    
  query-agent:
    build: .
    container_name: protokollfuehrer-query-agent
    env_file:
      - .env
    volumes:
      - .:/app
    # Stellt sicher, dass der PYTHONPATH beim Start gesetzt wird,
    # um die im Dockerfile isolierten Abhängigkeiten zu finden.
    command: /bin/bash -c "PYTHONPATH=$$PYTHON_DEPENDENCIES_PATH python query_agent.py"