version: '3.8'

services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # No volumes are mounted to ensure the code is copied during the build process
    # This resolves the ModuleNotFoundError by using the code baked into the image
    container_name: protokollfuehrer-agent