version: '3.8'

services:
  agent-cli-tool:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./protocols:/app/protocols
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    command: python main.py