version: '3.8'

services:
  agent-cli-tool:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./protocols:/app/protocols
    stdin_open: true
    tty: true
    command: python protocol_console.py