version: '3.8'

services:
  agent-cli-tool:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # NEU: DISPLAY wird explizit auf den Host-Resolver gesetzt
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      # Nur dieser Volume-Mount bleibt übrig:
      - ./protocols:/app/protocols
    # Stellt sicher, dass host.docker.internal zur Host-IP aufgelöst wird
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    command: python main.py