version: '3.8'

services:
  agent-cli-tool:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # NEU: 'environment:' wurde entfernt, um WSLg die automatische Zuweisung zu erlauben.
    volumes:
      - ./protocols:/app/protocols
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
    command: python main.py